import { images } from "@/assets/images";
import { Weather } from "./types";

export const data: Weather = { "timelines": { "daily": [{ "time": "2025-03-08T23:00:00Z", "values": { "cloudBaseAvg": 0.5, "cloudBaseMax": 1.6, "cloudBaseMin": 0, "cloudCeilingAvg": 4.7, "cloudCeilingMax": 11.5, "cloudCeilingMin": 0, "cloudCoverAvg": 100, "cloudCoverMax": 100, "cloudCoverMin": 98, "dewPointAvg": 23.6, "dewPointMax": 24.4, "dewPointMin": 22.8, "evapotranspirationAvg": 0.163, "evapotranspirationMax": 0.297, "evapotranspirationMin": 0.003, "evapotranspirationSum": 3.91, "freezingRainIntensityAvg": 0, "freezingRainIntensityMax": 0, "freezingRainIntensityMin": 0, "hailProbabilityAvg": 46.9, "hailProbabilityMax": 98.2, "hailProbabilityMin": 11.6, "hailSizeAvg": 4.9, "hailSizeMax": 9.82, "hailSizeMin": 0.27, "humidityAvg": 91, "humidityMax": 99, "humidityMin": 77, "iceAccumulationAvg": 0, "iceAccumulationLweAvg": 0, "iceAccumulationLweMax": 0, "iceAccumulationLweMin": 0, "iceAccumulationLweSum": 0, "iceAccumulationMax": 0, "iceAccumulationMin": 0, "iceAccumulationSum": 0, "moonriseTime": "2025-03-08T06:39:12Z", "moonsetTime": "2025-03-08T18:44:04Z", "precipitationProbabilityAvg": 12.3, "precipitationProbabilityMax": 45, "precipitationProbabilityMin": 0, "pressureSeaLevelAvg": 1010.45, "pressureSeaLevelMax": 1012.11, "pressureSeaLevelMin": 1008.24, "pressureSurfaceLevelAvg": 1001.81, "pressureSurfaceLevelMax": 1003.42, "pressureSurfaceLevelMin": 999.66, "rainAccumulationAvg": 0.11, "rainAccumulationLweAvg": 0.11, "rainAccumulationLweMax": 1.08, "rainAccumulationLweMin": 0, "rainAccumulationMax": 0.69, "rainAccumulationMin": 0, "rainAccumulationSum": 2.56, "rainIntensityAvg": 0.12, "rainIntensityMax": 1.08, "rainIntensityMin": 0, "sleetAccumulationAvg": 0, "sleetAccumulationLweAvg": 0, "sleetAccumulationLweMax": 0, "sleetAccumulationLweMin": 0, "sleetAccumulationLweSum": 0, "sleetAccumulationMax": 0, "sleetAccumulationMin": 0, "sleetIntensityAvg": 0, "sleetIntensityMax": 0, "sleetIntensityMin": 0, "snowAccumulationAvg": 0, "snowAccumulationLweAvg": 0, "snowAccumulationLweMax": 0, "snowAccumulationLweMin": 0, "snowAccumulationLweSum": 0, "snowAccumulationMax": 0, "snowAccumulationMin": 0, "snowAccumulationSum": 0, "snowIntensityAvg": 0, "snowIntensityMax": 0, "snowIntensityMin": 0, "sunriseTime": "2025-03-08T23:00:00Z", "sunsetTime": "2025-03-09T11:11:00Z", "temperatureApparentAvg": 26.4, "temperatureApparentMax": 32.7, "temperatureApparentMin": 23, "temperatureAvg": 25.3, "temperatureMax": 28.5, "temperatureMin": 23, "uvHealthConcernAvg": 0, "uvHealthConcernMax": 1, "uvHealthConcernMin": 0, "uvIndexAvg": 1, "uvIndexMax": 4, "uvIndexMin": 0, "visibilityAvg": 12.33, "visibilityMax": 16, "visibilityMin": 3.86, "weatherCodeMax": 1001, "weatherCodeMin": 1001, "windDirectionAvg": 166, "windGustAvg": 3.1, "windGustMax": 6.5, "windGustMin": 0.8, "windSpeedAvg": 1.3, "windSpeedMax": 2.6, "windSpeedMin": 0.5 } }, { "time": "2025-03-09T23:00:00Z", "values": { "cloudBaseAvg": 2.7, "cloudBaseMax": 9.5, "cloudBaseMin": 0, "cloudCeilingAvg": 9.9, "cloudCeilingMax": 14.6, "cloudCeilingMin": 0, "cloudCoverAvg": 94, "cloudCoverMax": 100, "cloudCoverMin": 53, "dewPointAvg": 23.4, "dewPointMax": 24.2, "dewPointMin": 22.6, "evapotranspirationAvg": 0.146, "evapotranspirationMax": 0.212, "evapotranspirationMin": 0.088, "evapotranspirationSum": 3.496, "freezingRainIntensityAvg": 0, "freezingRainIntensityMax": 0, "freezingRainIntensityMin": 0, "hailProbabilityAvg": 49.4, "hailProbabilityMax": 92.7, "hailProbabilityMin": 1.3, "hailSizeAvg": 4.16, "hailSizeMax": 9.95, "hailSizeMin": 0.94, "humidityAvg": 86, "humidityMax": 99, "humidityMin": 69, "iceAccumulationAvg": 0, "iceAccumulationLweAvg": 0, "iceAccumulationLweMax": 0, "iceAccumulationLweMin": 0, "iceAccumulationLweSum": 0, "iceAccumulationMax": 0, "iceAccumulationMin": 0, "iceAccumulationSum": 0, "moonriseTime": "2025-03-09T07:37:13Z", "moonsetTime": "2025-03-09T19:42:28Z", "precipitationProbabilityAvg": 3.8, "precipitationProbabilityMax": 20, "precipitationProbabilityMin": 0, "pressureSeaLevelAvg": 1010.37, "pressureSeaLevelMax": 1012.86, "pressureSeaLevelMin": 1008.08, "pressureSurfaceLevelAvg": 1001.73, "pressureSurfaceLevelMax": 1004.16, "pressureSurfaceLevelMin": 999.51, "rainAccumulationAvg": 0, "rainAccumulationLweAvg": 0.02, "rainAccumulationLweMax": 0.17, "rainAccumulationLweMin": 0, "rainAccumulationMax": 0, "rainAccumulationMin": 0, "rainAccumulationSum": 0, "rainIntensityAvg": 0.02, "rainIntensityMax": 0.17, "rainIntensityMin": 0, "sleetAccumulationAvg": 0, "sleetAccumulationLweAvg": 0, "sleetAccumulationLweMax": 0, "sleetAccumulationLweMin": 0, "sleetAccumulationLweSum": 0, "sleetAccumulationMax": 0, "sleetAccumulationMin": 0, "sleetIntensityAvg": 0, "sleetIntensityMax": 0, "sleetIntensityMin": 0, "snowAccumulationAvg": 0, "snowAccumulationLweAvg": 0, "snowAccumulationLweMax": 0, "snowAccumulationLweMin": 0, "snowAccumulationLweSum": 0, "snowAccumulationMax": 0, "snowAccumulationMin": 0, "snowAccumulationSum": 0, "snowIntensityAvg": 0, "snowIntensityMax": 0, "snowIntensityMin": 0, "sunriseTime": "2025-03-09T23:00:00Z", "sunsetTime": "2025-03-10T11:10:00Z", "temperatureApparentAvg": 27.7, "temperatureApparentMax": 35, "temperatureApparentMin": 22.7, "temperatureAvg": 26, "temperatureMax": 30, "temperatureMin": 22.7, "uvHealthConcernAvg": 1, "uvHealthConcernMax": 3, "uvHealthConcernMin": 0, "uvIndexAvg": 2, "uvIndexMax": 9, "uvIndexMin": 0, "visibilityAvg": 12.18, "visibilityMax": 16, "visibilityMin": 0.85, "weatherCodeMax": 1001, "weatherCodeMin": 1001, "windDirectionAvg": 140, "windGustAvg": 3.8, "windGustMax": 8.1, "windGustMin": 0.6, "windSpeedAvg": 1.6, "windSpeedMax": 2.9, "windSpeedMin": 0.3 } }, { "time": "2025-03-10T23:00:00Z", "values": { "cloudBaseAvg": 2.2, "cloudBaseMax": 13.1, "cloudBaseMin": 0.2, "cloudCeilingAvg": 8.9, "cloudCeilingMax": 15.2, "cloudCeilingMin": 0, "cloudCoverAvg": 86, "cloudCoverMax": 100, "cloudCoverMin": 28, "dewPointAvg": 23.7, "dewPointMax": 24.7, "dewPointMin": 22.6, "evapotranspirationAvg": 0.144, "evapotranspirationMax": 0.192, "evapotranspirationMin": 0.096, "evapotranspirationSum": 3.457, "freezingRainIntensityAvg": 0, "freezingRainIntensityMax": 0, "freezingRainIntensityMin": 0, "hailProbabilityAvg": 55.4, "hailProbabilityMax": 84.4, "hailProbabilityMin": 0.1, "hailSizeAvg": 5.09, "hailSizeMax": 9.16, "hailSizeMin": 0.66, "humidityAvg": 86, "humidityMax": 99, "humidityMin": 70, "iceAccumulationAvg": 0, "iceAccumulationLweAvg": 0, "iceAccumulationLweMax": 0, "iceAccumulationLweMin": 0, "iceAccumulationLweSum": 0, "iceAccumulationMax": 0, "iceAccumulationMin": 0, "iceAccumulationSum": 0, "moonriseTime": "2025-03-10T08:30:26Z", "moonsetTime": "2025-03-10T20:37:11Z", "precipitationProbabilityAvg": 11.3, "precipitationProbabilityMax": 25, "precipitationProbabilityMin": 0, "pressureSeaLevelAvg": 1009.19, "pressureSeaLevelMax": 1011.69, "pressureSeaLevelMin": 1006.07, "pressureSurfaceLevelAvg": 1000.58, "pressureSurfaceLevelMax": 1002.97, "pressureSurfaceLevelMin": 997.58, "rainAccumulationAvg": 0.52, "rainAccumulationLweAvg": 0.56, "rainAccumulationLweMax": 5.42, "rainAccumulationLweMin": 0, "rainAccumulationMax": 7.7, "rainAccumulationMin": 0, "rainAccumulationSum": 12.59, "rainIntensityAvg": 0.56, "rainIntensityMax": 5.42, "rainIntensityMin": 0, "sleetAccumulationAvg": 0, "sleetAccumulationLweAvg": 0, "sleetAccumulationLweMax": 0, "sleetAccumulationLweMin": 0, "sleetAccumulationLweSum": 0, "sleetAccumulationMax": 0, "sleetAccumulationMin": 0, "sleetIntensityAvg": 0, "sleetIntensityMax": 0, "sleetIntensityMin": 0, "snowAccumulationAvg": 0, "snowAccumulationLweAvg": 0, "snowAccumulationLweMax": 0, "snowAccumulationLweMin": 0, "snowAccumulationLweSum": 0, "snowAccumulationMax": 0, "snowAccumulationMin": 0, "snowAccumulationSum": 0, "snowIntensityAvg": 0, "snowIntensityMax": 0, "snowIntensityMin": 0, "sunriseTime": "2025-03-10T23:00:00Z", "sunsetTime": "2025-03-11T11:10:00Z", "temperatureApparentAvg": 28.4, "temperatureApparentMax": 35.6, "temperatureApparentMin": 22.7, "temperatureAvg": 26.3, "temperatureMax": 30.2, "temperatureMin": 22.7, "uvHealthConcernAvg": 1, "uvHealthConcernMax": 3, "uvHealthConcernMin": 0, "uvIndexAvg": 2, "uvIndexMax": 9, "uvIndexMin": 0, "visibilityAvg": 11.42, "visibilityMax": 16, "visibilityMin": 1.27, "weatherCodeMax": 1001, "weatherCodeMin": 1001, "windDirectionAvg": 179, "windGustAvg": 3.9, "windGustMax": 8.2, "windGustMin": 0.9, "windSpeedAvg": 1.7, "windSpeedMax": 3.3, "windSpeedMin": 0.5 } }, { "time": "2025-03-11T23:00:00Z", "values": { "cloudBaseAvg": 2.9, "cloudBaseMax": 10.2, "cloudBaseMin": 0.3, "cloudCeilingAvg": 11.1, "cloudCeilingMax": 15, "cloudCeilingMin": 0.8, "cloudCoverAvg": 99, "cloudCoverMax": 100, "cloudCoverMin": 92, "dewPointAvg": 23.9, "dewPointMax": 24.8, "dewPointMin": 22.4, "evapotranspirationAvg": 0.131, "evapotranspirationMax": 0.164, "evapotranspirationMin": 0.108, "evapotranspirationSum": 3.143, "freezingRainIntensityAvg": 0, "freezingRainIntensityMax": 0, "freezingRainIntensityMin": 0, "hailProbabilityAvg": 49.7, "hailProbabilityMax": 91.1, "hailProbabilityMin": 4.8, "hailSizeAvg": 5.66, "hailSizeMax": 10, "hailSizeMin": 0, "humidityAvg": 89, "humidityMax": 99, "humidityMin": 76, "iceAccumulationAvg": 0, "iceAccumulationLweAvg": 0, "iceAccumulationLweMax": 0, "iceAccumulationLweMin": 0, "iceAccumulationLweSum": 0, "iceAccumulationMax": 0, "iceAccumulationMin": 0, "iceAccumulationSum": 0, "moonriseTime": "2025-03-11T09:17:37Z", "moonsetTime": "2025-03-11T21:26:53Z", "precipitationProbabilityAvg": 8.3, "precipitationProbabilityMax": 30, "precipitationProbabilityMin": 0, "pressureSeaLevelAvg": 1008.97, "pressureSeaLevelMax": 1011.38, "pressureSeaLevelMin": 1006.65, "pressureSurfaceLevelAvg": 1000.37, "pressureSurfaceLevelMax": 1002.75, "pressureSurfaceLevelMin": 998.08, "rainAccumulationAvg": 0.3, "rainAccumulationLweAvg": 0.39, "rainAccumulationLweMax": 4.87, "rainAccumulationLweMin": 0, "rainAccumulationMax": 3.37, "rainAccumulationMin": 0, "rainAccumulationSum": 7.27, "rainIntensityAvg": 0.39, "rainIntensityMax": 4.87, "rainIntensityMin": 0, "sleetAccumulationAvg": 0, "sleetAccumulationLweAvg": 0, "sleetAccumulationLweMax": 0, "sleetAccumulationLweMin": 0, "sleetAccumulationLweSum": 0, "sleetAccumulationMax": 0, "sleetAccumulationMin": 0, "sleetIntensityAvg": 0, "sleetIntensityMax": 0, "sleetIntensityMin": 0, "snowAccumulationAvg": 0, "snowAccumulationLweAvg": 0, "snowAccumulationLweMax": 0, "snowAccumulationLweMin": 0, "snowAccumulationLweSum": 0, "snowAccumulationMax": 0, "snowAccumulationMin": 0, "snowAccumulationSum": 0, "snowIntensityAvg": 0, "snowIntensityMax": 0, "snowIntensityMin": 0, "sunriseTime": "2025-03-11T23:00:00Z", "sunsetTime": "2025-03-12T11:10:00Z", "temperatureApparentAvg": 27.6, "temperatureApparentMax": 35, "temperatureApparentMin": 22.5, "temperatureAvg": 25.9, "temperatureMax": 29.4, "temperatureMin": 22.5, "uvHealthConcernAvg": 0, "uvHealthConcernMax": 2, "uvHealthConcernMin": 0, "uvIndexAvg": 2, "uvIndexMax": 7, "uvIndexMin": 0, "visibilityAvg": 15.14, "visibilityMax": 16, "visibilityMin": 7.2, "weatherCodeMax": 1001, "weatherCodeMin": 1001, "windDirectionAvg": 241, "windGustAvg": 3.2, "windGustMax": 6.4, "windGustMin": 1.5, "windSpeedAvg": 1.3, "windSpeedMax": 2.4, "windSpeedMin": 0.3 } }, { "time": "2025-03-12T23:00:00Z", "values": { "cloudBaseAvg": 1.2, "cloudBaseMax": 3.8, "cloudBaseMin": 0.4, "cloudCeilingAvg": 9.8, "cloudCeilingMax": 12.5, "cloudCeilingMin": 0.8, "cloudCoverAvg": 100, "cloudCoverMax": 100, "cloudCoverMin": 99, "dewPointAvg": 23.8, "dewPointMax": 25, "dewPointMin": 23, "evapotranspirationAvg": 0.126, "evapotranspirationMax": 0.157, "evapotranspirationMin": 0.106, "evapotranspirationSum": 3.024, "freezingRainIntensityAvg": 0, "freezingRainIntensityMax": 0, "freezingRainIntensityMin": 0, "hailProbabilityAvg": 61.3, "hailProbabilityMax": 89.1, "hailProbabilityMin": 2.7, "hailSizeAvg": 4.02, "hailSizeMax": 9.55, "hailSizeMin": 1.12, "humidityAvg": 89, "humidityMax": 96, "humidityMin": 76, "iceAccumulationAvg": 0, "iceAccumulationLweAvg": 0, "iceAccumulationLweMax": 0, "iceAccumulationLweMin": 0, "iceAccumulationLweSum": 0, "iceAccumulationMax": 0, "iceAccumulationMin": 0, "iceAccumulationSum": 0, "moonriseTime": "2025-03-12T10:00:24Z", "moonsetTime": "2025-03-12T22:13:26Z", "precipitationProbabilityAvg": 13.8, "precipitationProbabilityMax": 45, "precipitationProbabilityMin": 0, "pressureSeaLevelAvg": 1009.24, "pressureSeaLevelMax": 1011.46, "pressureSeaLevelMin": 1007.94, "pressureSurfaceLevelAvg": 1000.66, "pressureSurfaceLevelMax": 1002.88, "pressureSurfaceLevelMin": 999.36, "rainAccumulationAvg": 0.31, "rainAccumulationLweAvg": 0.02, "rainAccumulationLweMax": 0.27, "rainAccumulationLweMin": 0, "rainAccumulationMax": 1.84, "rainAccumulationMin": 0, "rainAccumulationSum": 7.44, "rainIntensityAvg": 0.05, "rainIntensityMax": 0.27, "rainIntensityMin": 0, "sleetAccumulationAvg": 0, "sleetAccumulationLweAvg": 0, "sleetAccumulationLweMax": 0, "sleetAccumulationLweMin": 0, "sleetAccumulationLweSum": 0, "sleetAccumulationMax": 0, "sleetAccumulationMin": 0, "sleetIntensityAvg": 0, "sleetIntensityMax": 0, "sleetIntensityMin": 0, "snowAccumulationAvg": 0, "snowAccumulationLweAvg": 0, "snowAccumulationLweMax": 0, "snowAccumulationLweMin": 0, "snowAccumulationLweSum": 0, "snowAccumulationMax": 0, "snowAccumulationMin": 0, "snowAccumulationSum": 0, "snowIntensityAvg": 0, "snowIntensityMax": 0, "snowIntensityMin": 0, "sunriseTime": "2025-03-12T23:00:00Z", "sunsetTime": "2025-03-13T11:09:00Z", "temperatureApparentAvg": 27.4, "temperatureApparentMax": 35.9, "temperatureApparentMin": 23.8, "temperatureAvg": 25.8, "temperatureMax": 29.8, "temperatureMin": 23.8, "uvHealthConcernAvg": 2, "uvHealthConcernMax": 5, "uvHealthConcernMin": 0, "uvIndexAvg": 5, "uvIndexMax": 12, "uvIndexMin": 0, "visibilityAvg": 15.66, "visibilityMax": 16, "visibilityMin": 13.26, "weatherCodeMax": 1001, "weatherCodeMin": 1001, "windDirectionAvg": 246, "windGustAvg": 4.1, "windGustMax": 7, "windGustMin": 1.9, "windSpeedAvg": 1.9, "windSpeedMax": 3.4, "windSpeedMin": 1 } }, { "time": "2025-03-13T23:00:00Z", "values": { "cloudBaseAvg": 1.7, "cloudBaseMax": 5.4, "cloudBaseMin": 0.5, "cloudCeilingAvg": 11.7, "cloudCeilingMax": 12.7, "cloudCeilingMin": 8.6, "cloudCoverAvg": 100, "cloudCoverMax": 100, "cloudCoverMin": 100, "dewPointAvg": 23.6, "dewPointMax": 24.7, "dewPointMin": 22.8, "evapotranspirationAvg": 0.121, "evapotranspirationMax": 0.142, "evapotranspirationMin": 0.102, "evapotranspirationSum": 2.898, "freezingRainIntensityAvg": 0, "freezingRainIntensityMax": 0, "freezingRainIntensityMin": 0, "hailProbabilityAvg": 53.4, "hailProbabilityMax": 95.6, "hailProbabilityMin": 3.9, "hailSizeAvg": 5.04, "hailSizeMax": 9.88, "hailSizeMin": 0.01, "humidityAvg": 89, "humidityMax": 97, "humidityMin": 78, "iceAccumulationAvg": 0, "iceAccumulationLweAvg": 0, "iceAccumulationLweMax": 0, "iceAccumulationLweMin": 0, "iceAccumulationLweSum": 0, "iceAccumulationMax": 0, "iceAccumulationMin": 0, "iceAccumulationSum": 0, "moonriseTime": "2025-03-13T10:40:56Z", "moonsetTime": "2025-03-13T22:57:46Z", "precipitationProbabilityAvg": 10, "precipitationProbabilityMax": 35, "precipitationProbabilityMin": 0, "pressureSeaLevelAvg": 1009.84, "pressureSeaLevelMax": 1011.62, "pressureSeaLevelMin": 1007.5, "pressureSurfaceLevelAvg": 1001.25, "pressureSurfaceLevelMax": 1003.02, "pressureSurfaceLevelMin": 998.99, "rainAccumulationAvg": 0.28, "rainAccumulationLweAvg": 0.02, "rainAccumulationLweMax": 0.25, "rainAccumulationLweMin": 0, "rainAccumulationMax": 1.14, "rainAccumulationMin": 0, "rainAccumulationSum": 6.63, "rainIntensityAvg": 0.07, "rainIntensityMax": 0.25, "rainIntensityMin": 0, "sleetAccumulationAvg": 0, "sleetAccumulationLweAvg": 0, "sleetAccumulationLweMax": 0, "sleetAccumulationLweMin": 0, "sleetAccumulationLweSum": 0, "sleetAccumulationMax": 0, "sleetAccumulationMin": 0, "sleetIntensityAvg": 0, "sleetIntensityMax": 0, "sleetIntensityMin": 0, "snowAccumulationAvg": 0, "snowAccumulationLweAvg": 0, "snowAccumulationLweMax": 0, "snowAccumulationLweMin": 0, "snowAccumulationLweSum": 0, "snowAccumulationMax": 0, "snowAccumulationMin": 0, "snowAccumulationSum": 0, "snowIntensityAvg": 0, "snowIntensityMax": 0, "snowIntensityMin": 0, "sunriseTime": "2025-03-13T23:00:00Z", "sunsetTime": "2025-03-14T11:09:00Z", "temperatureApparentAvg": 27.3, "temperatureApparentMax": 34.1, "temperatureApparentMin": 23.3, "temperatureAvg": 25.7, "temperatureMax": 28.9, "temperatureMin": 23.3, "visibilityAvg": 14.36, "visibilityMax": 16, "visibilityMin": 8.32, "weatherCodeMax": 1001, "weatherCodeMin": 1001, "windDirectionAvg": 268, "windGustAvg": 3.8, "windGustMax": 8.4, "windGustMin": 2.1, "windSpeedAvg": 1.7, "windSpeedMax": 3.8, "windSpeedMin": 0.7 } }] }, "location": { "lat": -6.116966247558594, "lon": 106.15180969238281, "name": "Serang, Banten, Jawa, Indonesia", "type": "administrative" } }

export const weatherCodes: Record<string, any> = {
  weatherCode: {
    "0": "Tidak Diketahui",
    "1000": "Cerah, Cerah Terik",
    "1100": "Sebagian Besar Cerah",
    "1101": "Berawan Sebagian",
    "1102": "Sebagian Besar Berawan",
    "1001": "Berawan",
    "2000": "Berkabut",
    "2100": "Kabut Ringan",
    "4000": "Gerimis",
    "4001": "Hujan",
    "4200": "Hujan Ringan",
    "4201": "Hujan Lebat",
    "5000": "Salju",
    "5001": "Badai Salju",
    "5100": "Salju Ringan",
    "5101": "Salju Lebat",
    "6000": "Gerimis Beku",
    "6001": "Hujan Beku",
    "6200": "Hujan Beku Ringan",
    "6201": "Hujan Beku Lebat",
    "7000": "Butiran Es",
    "7101": "Butiran Es Lebat",
    "7102": "Butiran Es Ringan",
    "8000": "Badai Petir"
  },
  weatherIcon: {
    "1000": images[1000],
    "1001": images[1001],
    "1100": images[1100],
    "1101": images[1101],
    "1102": images[1102],
    "2000": images[2000],
    "2100": images[2100],
    "4000": images[4000],
    "4001": images[4001],
    "4200": images[4200],
    "4201": images[4201],
    "5000": images[5000],
    "5001": images[5001],
    "5100": images[5100],
    "5101": images[5101],
    "6000": images[6000],
    "6001": images[6001],
    "6200": images[6200],
    "6201": images[6201],
    "7000": images[7000],
    "7101": images[7101],
    "7102": images[7102],
    "8000": images[8000],
  },
"weatherCodeFullDay": {
  "0": "Unknown",
    "1000": "Clear, Sunny",
      "1100": "Mostly Clear",
        "1101": "Partly Cloudy",
          "1102": "Mostly Cloudy",
            "1001": "Cloudy",
              "1103": "Partly Cloudy and Mostly Clear",
                "2100": "Light Fog",
                  "2101": "Mostly Clear and Light Fog",
                    "2102": "Partly Cloudy and Light Fog",
                      "2103": "Mostly Cloudy and Light Fog",
                        "2106": "Mostly Clear and Fog",
                          "2107": "Partly Cloudy and Fog",
                            "2108": "Mostly Cloudy and Fog",
                              "2000": "Fog",
                                "4204": "Partly Cloudy and Drizzle",
                                  "4203": "Mostly Clear and Drizzle",
                                    "4205": "Mostly Cloudy and Drizzle",
                                      "4000": "Drizzle",
                                        "4200": "Light Rain",
                                          "4213": "Mostly Clear and Light Rain",
                                            "4214": "Partly Cloudy and Light Rain",
                                              "4215": "Mostly Cloudy and Light Rain",
                                                "4209": "Mostly Clear and Rain",
                                                  "4208": "Partly Cloudy and Rain",
                                                    "4210": "Mostly Cloudy and Rain",
                                                      "4001": "Rain",
                                                        "4211": "Mostly Clear and Heavy Rain",
                                                          "4202": "Partly Cloudy and Heavy Rain",
                                                            "4212": "Mostly Cloudy and Heavy Rain",
                                                              "4201": "Heavy Rain",
                                                                "5115": "Mostly Clear and Flurries",
                                                                  "5116": "Partly Cloudy and Flurries",
                                                                    "5117": "Mostly Cloudy and Flurries",
                                                                      "5001": "Flurries",
                                                                        "5100": "Light Snow",
                                                                          "5102": "Mostly Clear and Light Snow",
                                                                            "5103": "Partly Cloudy and Light Snow",
                                                                              "5104": "Mostly Cloudy and Light Snow",
                                                                                "5122": "Drizzle and Light Snow",
                                                                                  "5105": "Mostly Clear and Snow",
                                                                                    "5106": "Partly Cloudy and Snow",
                                                                                      "5107": "Mostly Cloudy and Snow",
                                                                                        "5000": "Snow",
                                                                                          "5101": "Heavy Snow",
                                                                                            "5119": "Mostly Clear and Heavy Snow",
                                                                                              "5120": "Partly Cloudy and Heavy Snow",
                                                                                                "5121": "Mostly Cloudy and Heavy Snow",
                                                                                                  "5110": "Drizzle and Snow",
                                                                                                    "5108": "Rain and Snow",
                                                                                                      "5114": "Snow and Freezing Rain",
                                                                                                        "5112": "Snow and Ice Pellets",
                                                                                                          "6000": "Freezing Drizzle",
                                                                                                            "6003": "Mostly Clear and Freezing drizzle",
                                                                                                              "6002": "Partly Cloudy and Freezing drizzle",
                                                                                                                "6004": "Mostly Cloudy and Freezing drizzle",
                                                                                                                  "6204": "Drizzle and Freezing Drizzle",
                                                                                                                    "6206": "Light Rain and Freezing Drizzle",
                                                                                                                      "6205": "Mostly Clear and Light Freezing Rain",
                                                                                                                        "6203": "Partly Cloudy and Light Freezing Rain",
                                                                                                                          "6209": "Mostly Cloudy and Light Freezing Rain",
                                                                                                                            "6200": "Light Freezing Rain",
                                                                                                                              "6213": "Mostly Clear and Freezing Rain",
                                                                                                                                "6214": "Partly Cloudy and Freezing Rain",
                                                                                                                                  "6215": "Mostly Cloudy and Freezing Rain",
                                                                                                                                    "6001": "Freezing Rain",
                                                                                                                                      "6212": "Drizzle and Freezing Rain",
                                                                                                                                        "6220": "Light Rain and Freezing Rain",
                                                                                                                                          "6222": "Rain and Freezing Rain",
                                                                                                                                            "6207": "Mostly Clear and Heavy Freezing Rain",
                                                                                                                                              "6202": "Partly Cloudy and Heavy Freezing Rain",
                                                                                                                                                "6208": "Mostly Cloudy and Heavy Freezing Rain",
                                                                                                                                                  "6201": "Heavy Freezing Rain",
                                                                                                                                                    "7110": "Mostly Clear and Light Ice Pellets",
                                                                                                                                                      "7111": "Partly Cloudy and Light Ice Pellets",
                                                                                                                                                        "7112": "Mostly Cloudy and Light Ice Pellets",
                                                                                                                                                          "7102": "Light Ice Pellets",
                                                                                                                                                            "7108": "Mostly Clear and Ice Pellets",
                                                                                                                                                              "7107": "Partly Cloudy and Ice Pellets",
                                                                                                                                                                "7109": "Mostly Cloudy and Ice Pellets",
                                                                                                                                                                  "7000": "Ice Pellets",
                                                                                                                                                                    "7105": "Drizzle and Ice Pellets",
                                                                                                                                                                      "7106": "Freezing Rain and Ice Pellets",
                                                                                                                                                                        "7115": "Light Rain and Ice Pellets",
                                                                                                                                                                          "7117": "Rain and Ice Pellets",
                                                                                                                                                                            "7103": "Freezing Rain and Heavy Ice Pellets",
                                                                                                                                                                              "7113": "Mostly Clear and Heavy Ice Pellets",
                                                                                                                                                                                "7114": "Partly Cloudy and Heavy Ice Pellets",
                                                                                                                                                                                  "7116": "Mostly Cloudy and Heavy Ice Pellets",
                                                                                                                                                                                    "7101": "Heavy Ice Pellets",
                                                                                                                                                                                      "8001": "Mostly Clear and Thunderstorm",
                                                                                                                                                                                        "8003": "Partly Cloudy and Thunderstorm",
                                                                                                                                                                                          "8002": "Mostly Cloudy and Thunderstorm",
                                                                                                                                                                                            "8000": "Thunderstorm"
},
"weatherCodeDay": {
  "0": "Unknown",
    "10000": "Clear, Sunny",
      "11000": "Mostly Clear",
        "11010": "Partly Cloudy",
          "11020": "Mostly Cloudy",
            "10010": "Cloudy",
              "11030": "Partly Cloudy and Mostly Clear",
                "21000": "Light Fog",
                  "21010": "Mostly Clear and Light Fog",
                    "21020": "Partly Cloudy and Light Fog",
                      "21030": "Mostly Cloudy and Light Fog",
                        "21060": "Mostly Clear and Fog",
                          "21070": "Partly Cloudy and Fog",
                            "21080": "Mostly Cloudy and Fog",
                              "20000": "Fog",
                                "42040": "Partly Cloudy and Drizzle",
                                  "42030": "Mostly Clear and Drizzle",
                                    "42050": "Mostly Cloudy and Drizzle",
                                      "40000": "Drizzle",
                                        "42000": "Light Rain",
                                          "42130": "Mostly Clear and Light Rain",
                                            "42140": "Partly Cloudy and Light Rain",
                                              "42150": "Mostly Cloudy and Light Rain",
                                                "42090": "Mostly Clear and Rain",
                                                  "42080": "Partly Cloudy and Rain",
                                                    "42100": "Mostly Cloudy and Rain",
                                                      "40010": "Rain",
                                                        "42110": "Mostly Clear and Heavy Rain",
                                                          "42020": "Partly Cloudy and Heavy Rain",
                                                            "42120": "Mostly Cloudy and Heavy Rain",
                                                              "42010": "Heavy Rain",
                                                                "51150": "Mostly Clear and Flurries",
                                                                  "51160": "Partly Cloudy and Flurries",
                                                                    "51170": "Mostly Cloudy and Flurries",
                                                                      "50010": "Flurries",
                                                                        "51000": "Light Snow",
                                                                          "51020": "Mostly Clear and Light Snow",
                                                                            "51030": "Partly Cloudy and Light Snow",
                                                                              "51040": "Mostly Cloudy and Light Snow",
                                                                                "51220": "Drizzle and Light Snow",
                                                                                  "51050": "Mostly Clear and Snow",
                                                                                    "51060": "Partly Cloudy and Snow",
                                                                                      "51070": "Mostly Cloudy and Snow",
                                                                                        "50000": "Snow",
                                                                                          "51010": "Heavy Snow",
                                                                                            "51190": "Mostly Clear and Heavy Snow",
                                                                                              "51200": "Partly Cloudy and Heavy Snow",
                                                                                                "51210": "Mostly Cloudy and Heavy Snow",
                                                                                                  "51100": "Drizzle and Snow",
                                                                                                    "51080": "Rain and Snow",
                                                                                                      "51140": "Snow and Freezing Rain",
                                                                                                        "51120": "Snow and Ice Pellets",
                                                                                                          "60000": "Freezing Drizzle",
                                                                                                            "60030": "Mostly Clear and Freezing drizzle",
                                                                                                              "60020": "Partly Cloudy and Freezing drizzle",
                                                                                                                "60040": "Mostly Cloudy and Freezing drizzle",
                                                                                                                  "62040": "Drizzle and Freezing Drizzle",
                                                                                                                    "62060": "Light Rain and Freezing Drizzle",
                                                                                                                      "62050": "Mostly Clear and Light Freezing Rain",
                                                                                                                        "62030": "Partly Cloudy and Light Freezing Rain",
                                                                                                                          "62090": "Mostly Cloudy and Light Freezing Rain",
                                                                                                                            "62000": "Light Freezing Rain",
                                                                                                                              "62130": "Mostly Clear and Freezing Rain",
                                                                                                                                "62140": "Partly Cloudy and Freezing Rain",
                                                                                                                                  "62150": "Mostly Cloudy and Freezing Rain",
                                                                                                                                    "60010": "Freezing Rain",
                                                                                                                                      "62120": "Drizzle and Freezing Rain",
                                                                                                                                        "62200": "Light Rain and Freezing Rain",
                                                                                                                                          "62220": "Rain and Freezing Rain",
                                                                                                                                            "62070": "Mostly Clear and Heavy Freezing Rain",
                                                                                                                                              "62020": "Partly Cloudy and Heavy Freezing Rain",
                                                                                                                                                "62080": "Mostly Cloudy and Heavy Freezing Rain",
                                                                                                                                                  "62010": "Heavy Freezing Rain",
                                                                                                                                                    "71100": "Mostly Clear and Light Ice Pellets",
                                                                                                                                                      "71110": "Partly Cloudy and Light Ice Pellets",
                                                                                                                                                        "71120": "Mostly Cloudy and Light Ice Pellets",
                                                                                                                                                          "71020": "Light Ice Pellets",
                                                                                                                                                            "71080": "Mostly Clear and Ice Pellets",
                                                                                                                                                              "71070": "Partly Cloudy and Ice Pellets",
                                                                                                                                                                "71090": "Mostly Cloudy and Ice Pellets",
                                                                                                                                                                  "70000": "Ice Pellets",
                                                                                                                                                                    "71050": "Drizzle and Ice Pellets",
                                                                                                                                                                      "71060": "Freezing Rain and Ice Pellets",
                                                                                                                                                                        "71150": "Light Rain and Ice Pellets",
                                                                                                                                                                          "71170": "Rain and Ice Pellets",
                                                                                                                                                                            "71030": "Freezing Rain and Heavy Ice Pellets",
                                                                                                                                                                              "71130": "Mostly Clear and Heavy Ice Pellets",
                                                                                                                                                                                "71140": "Partly Cloudy and Heavy Ice Pellets",
                                                                                                                                                                                  "71160": "Mostly Cloudy and Heavy Ice Pellets",
                                                                                                                                                                                    "71010": "Heavy Ice Pellets",
                                                                                                                                                                                      "80010": "Mostly Clear and Thunderstorm",
                                                                                                                                                                                        "80030": "Partly Cloudy and Thunderstorm",
                                                                                                                                                                                          "80020": "Mostly Cloudy and Thunderstorm",
                                                                                                                                                                                            "80000": "Thunderstorm"
},
"weatherCodeNight": {
  "0": "Unknown",
    "10001": "Clear",
      "11001": "Mostly Clear",
        "11011": "Partly Cloudy",
          "11021": "Mostly Cloudy",
            "10011": "Cloudy",
              "11031": "Partly Cloudy and Mostly Clear",
                "21001": "Light Fog",
                  "21011": "Mostly Clear and Light Fog",
                    "21021": "Partly Cloudy and Light Fog",
                      "21031": "Mostly Cloudy and Light Fog",
                        "21061": "Mostly Clear and Fog",
                          "21071": "Partly Cloudy and Fog",
                            "21081": "Mostly Cloudy and Fog",
                              "20001": "Fog",
                                "42041": "Partly Cloudy and Drizzle",
                                  "42031": "Mostly Clear and Drizzle",
                                    "42051": "Mostly Cloudy and Drizzle",
                                      "40001": "Drizzle",
                                        "42001": "Light Rain",
                                          "42131": "Mostly Clear and Light Rain",
                                            "42141": "Partly Cloudy and Light Rain",
                                              "42151": "Mostly Cloudy and Light Rain",
                                                "42091": "Mostly Clear and Rain",
                                                  "42081": "Partly Cloudy and Rain",
                                                    "42101": "Mostly Cloudy and Rain",
                                                      "40011": "Rain",
                                                        "42111": "Mostly Clear and Heavy Rain",
                                                          "42021": "Partly Cloudy and Heavy Rain",
                                                            "42121": "Mostly Cloudy and Heavy Rain",
                                                              "42011": "Heavy Rain",
                                                                "51151": "Mostly Clear and Flurries",
                                                                  "51161": "Partly Cloudy and Flurries",
                                                                    "51171": "Mostly Cloudy and Flurries",
                                                                      "50011": "Flurries",
                                                                        "51001": "Light Snow",
                                                                          "51021": "Mostly Clear and Light Snow",
                                                                            "51031": "Partly Cloudy and Light Snow",
                                                                              "51041": "Mostly Cloudy and Light Snow",
                                                                                "51221": "Drizzle and Light Snow",
                                                                                  "51051": "Mostly Clear and Snow",
                                                                                    "51061": "Partly Cloudy and Snow",
                                                                                      "51071": "Mostly Cloudy and Snow",
                                                                                        "50001": "Snow",
                                                                                          "51011": "Heavy Snow",
                                                                                            "51191": "Mostly Clear and Heavy Snow",
                                                                                              "51201": "Partly Cloudy and Heavy Snow",
                                                                                                "51211": "Mostly Cloudy and Heavy Snow",
                                                                                                  "51101": "Drizzle and Snow",
                                                                                                    "51081": "Rain and Snow",
                                                                                                      "51141": "Snow and Freezing Rain",
                                                                                                        "51121": "Snow and Ice Pellets",
                                                                                                          "60001": "Freezing Drizzle",
                                                                                                            "60031": "Mostly Clear and Freezing drizzle",
                                                                                                              "60021": "Partly Cloudy and Freezing drizzle",
                                                                                                                "60041": "Mostly Cloudy and Freezing drizzle",
                                                                                                                  "62041": "Drizzle and Freezing Drizzle",
                                                                                                                    "62061": "Light Rain and Freezing Drizzle",
                                                                                                                      "62051": "Mostly Clear and Light Freezing Rain",
                                                                                                                        "62031": "Partly cloudy and Light Freezing Rain",
                                                                                                                          "62091": "Mostly Cloudy and Light Freezing Rain",
                                                                                                                            "62001": "Light Freezing Rain",
                                                                                                                              "62131": "Mostly Clear and Freezing Rain",
                                                                                                                                "62141": "Partly Cloudy and Freezing Rain",
                                                                                                                                  "62151": "Mostly Cloudy and Freezing Rain",
                                                                                                                                    "60011": "Freezing Rain",
                                                                                                                                      "62121": "Drizzle and Freezing Rain",
                                                                                                                                        "62201": "Light Rain and Freezing Rain",
                                                                                                                                          "62221": "Rain and Freezing Rain",
                                                                                                                                            "62071": "Mostly Clear and Heavy Freezing Rain",
                                                                                                                                              "62021": "Partly Cloudy and Heavy Freezing Rain",
                                                                                                                                                "62081": "Mostly Cloudy and Heavy Freezing Rain",
                                                                                                                                                  "62011": "Heavy Freezing Rain",
                                                                                                                                                    "71101": "Mostly Clear and Light Ice Pellets",
                                                                                                                                                      "71111": "Partly Cloudy and Light Ice Pellets",
                                                                                                                                                        "71121": "Mostly Cloudy and Light Ice Pellets",
                                                                                                                                                          "71021": "Light Ice Pellets",
                                                                                                                                                            "71081": "Mostly Clear and Ice Pellets",
                                                                                                                                                              "71071": "Partly Cloudy and Ice Pellets",
                                                                                                                                                                "71091": "Mostly Cloudy and Ice Pellets",
                                                                                                                                                                  "70001": "Ice Pellets",
                                                                                                                                                                    "71051": "Drizzle and Ice Pellets",
                                                                                                                                                                      "71061": "Freezing Rain and Ice Pellets",
                                                                                                                                                                        "71151": "Light Rain and Ice Pellets",
                                                                                                                                                                          "71171": "Rain and Ice Pellets",
                                                                                                                                                                            "71031": "Freezing Rain and Heavy Ice Pellets",
                                                                                                                                                                              "71131": "Mostly Clear and Heavy Ice Pellets",
                                                                                                                                                                                "71141": "Partly Cloudy and Heavy Ice Pellets",
                                                                                                                                                                                  "71161": "Mostly Cloudy and Heavy Ice Pellets",
                                                                                                                                                                                    "71011": "Heavy Ice Pellets",
                                                                                                                                                                                      "80011": "Mostly Clear and Thunderstorm",
                                                                                                                                                                                        "80031": "Partly Cloudy and Thunderstorm",
                                                                                                                                                                                          "80021": "Mostly Cloudy and Thunderstorm",
                                                                                                                                                                                            "80001": "Thunderstorm"
}
}
